// This file is automatically generated. Do not edit it directly.
// DISABLED: Migrated to Spring Boot backend
// Keeping this file to prevent import errors, but Supabase is no longer used

import type { Database } from './types';

// Mock Supabase client to prevent errors in files that still import it
// These imports should eventually be removed
export const supabase = {
  from: () => {
    console.warn('Supabase is disabled. Use Spring Boot API instead.');
    return {
      select: () => Promise.resolve({ data: [], error: null }),
      insert: () => Promise.resolve({ data: null, error: null }),
      update: () => Promise.resolve({ data: null, error: null }),
      delete: () => Promise.resolve({ data: null, error: null }),
      eq: function() { return this; },
      single: () => Promise.resolve({ data: null, error: null }),
    };
  },
  auth: {
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    signOut: () => Promise.resolve({ error: null }),
    signInWithPassword: () => Promise.resolve({ data: null, error: null }),
  },
  storage: {
    from: () => ({
      createSignedUrl: () => Promise.resolve({ data: { signedUrl: '' }, error: null }),
      upload: () => Promise.resolve({ data: null, error: null }),
    })
  }
} as any;
